@username=INPUT_USERNAME
@password=INPUT_PASSWORD
@pin_transaksi=INPUT_PIN_TRANSAKSI


### Login
GET http://localhost:3000/api/agenbni46/v1/getLogin?username={{username}}&password={{password}}

### Login Proxy
GET http://localhost:3000/api/agenbni46/v1/getLogin?proxy=true

### Logout
GET http://localhost:3000/api/agenbni46/v1/getLogout?

### Transaksi Bsa Transfer
GET http://localhost:3000/api/agenbni46/v1/getTransaksiBsaTransfer?no_rekening=0147025803690147&nominal=10000&pin_transaksi={{pin_transaksi}}

### Transaksi Bsa Transfer
GET http://localhost:3000/api/agenbni46/v1/getTransaksiBsaTransfer?no_rekening=0147025803690147&nominal=10000&pin_transaksi={{pin_transaksi}}&confirm=true

### Transaksi Bsa Transfer Non Bni
GET http://localhost:3000/api/agenbni46/v1/getTransaksiBsaTransferNonBni?no_rekening=0147025803690147&nominal=10000&bank_code=008&pin_transaksi={{pin_transaksi}}

### Transaksi Bsa Transfer Non Bni
GET http://localhost:3000/api/agenbni46/v1/getTransaksiBsaTransferNonBni?no_rekening=0147025803690147&nominal=10000&bank_code=008&pin_transaksi={{pin_transaksi}}&confirm=true

### Transaksi Transfer Va Billing
GET http://localhost:3000/api/agenbni46/v1/getTransaksiTransferVaBilling?no_rekening=0147025803690147&pin_transaksi={{pin_transaksi}}

### Transaksi Transfer Va Billing
GET http://localhost:3000/api/agenbni46/v1/getTransaksiTransferVaBilling?no_rekening=0147025803690147&pin_transaksi={{pin_transaksi}}&confirm=true

### Transaksi Pembelian Pln Token
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembelianPlnToken?cust_no=014702580369&pin_transaksi={{pin_transaksi}}

### Transaksi Pembelian Pln Token
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembelianPlnToken?cust_no=014702580369&pin_transaksi={{pin_transaksi}}&confirm=true

### Transaksi Pembelian Pln Token Advice
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembelianPlnTokenAdvice?cust_no=014702580369&no_reff=0147025803690147&pin_transaksi={{pin_transaksi}}

### Transaksi Pembelian Pulsa
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembelianPulsa?operator=XL_REG&nominal=5000&msisdn=087758437457&pin_transaksi={{pin_transaksi}}

### Transaksi Pembelian Prepaid Data
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembelianPrepaidData?operator=XL_DATA&nominal=XL+Data+Xtra+Combo+5GB+%282G%2F3G%2F4G%29+%2B+5GB+%28Youtube%29%2C+20Mnt+%28Anynet%29%2C+30hr%3BXL_07&msisdn=087758437457&pin_transaksi={{pin_transaksi}}

### Transaksi Pembelian Gopay
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembelianGopay?payment_type=GOPAY_DRIVER&billingId1=087758437457&amount=10000&pin_transaksi={{pin_transaksi}}

### Transaksi Pembelian Agen Penerbangan
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembelianAgenPenerbangan?operator=CITILINK_AGENT&nominal=10.000.000%2C00%3B10000000&msisdn=0147025803690147&pin_transaksi={{pin_transaksi}}

### Transaksi Pembelian Isaku
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembelianIsaku?VANumber=087758437457&BillAmount=10000&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Pln Pascabayar
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranPlnPascabayar?id_pelanggan=321654987321&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Pln Pascabayar
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranPlnPascabayar?id_pelanggan=321654987321&pin_transaksi={{pin_transaksi}}&confirm=true

### Transaksi Pembayaran Pln Pascabayar Nt
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranPlnPascabayarNt?no_reg=321654987&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Pascabayar
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranPascabayar?operator=XPLOR&no_hp=087758437457&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Telkom
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranTelkom?kode_area=0357&no_telp=882688&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Cc Bni
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranCcBni?operator=0&no_cc=0147025803690147&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Cc Bni O
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranCcBniO?bank_code=GE&no_cc=0147025803690147&nominal=10000&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Loan
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranLoan?bank_code=CITIBANK_PL&no_cc=0147025803690147&nominal=10000&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Airline
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranAirline?maskapai=CITILINK&billing_id=0147025803690147&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Tv Berlangganan
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranTvBerlangganan?provider=1&id_pelanggan=0147025803690147&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Internet
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranInternet?provider=SPEEDY&no_billing=321654987321&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Zis Qurban
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranZisQurban?tipe_layanan=INFA&badan_amil=INFAQ_ACT&nominal=10000&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Insurance
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranInsurance?payment_type=1&accountNum=32165497654&amount=321654987321&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Insurance Bni Life
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranInsuranceBniLife?provider=BNILIFE_PREMI_PERTAMA&id_pelanggan=321654978&nominal=10000&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Va Bpjs Kesehatan
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranVaBpjsKesehatan?billing_id=321654987&months=1&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Bpjs Ketenagakerjaan Bpu
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranBpjsKetenagakerjaanBpu?TipePembayaran=BPJS_TKBPU&billingId1=321654987&numberOfMonthsOfBills=6&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Kereta Api
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranKeretaApi?kode_pembayaran=321654987&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Pdam
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranPdam?nama_perusahaan=1%7CAETRA%7CAETRA%7C1302%7CMitracom%7CNON_AGGREGATOR%7C1&billing=321654987&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Multifinance
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranMultifinance?providerId=ACC_FINANCE&billingId=321654987&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Bumiputera
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranBumiputera?payment_type=BUMIPUTERA_PERTAMA&billing_id=321654987&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Epbb
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranEpbb?PembayaranPajak=PBB&billing_id=321654987&tahun=2022&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Jiwasraya
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranJiwasraya?billing_id=321654987&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Railink
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranRailink?billing_id=321654987&pin_transaksi={{pin_transaksi}}

### Transaksi Pembayaran Pembayaran Mpn
GET http://localhost:3000/api/agenbni46/v1/getTransaksiPembayaranPembayaranMpn?h_billingId=321654987321654&pin_transaksi={{pin_transaksi}}

### Check Balance
GET http://localhost:3000/api/agenbni46/v1/getCheckBalance?

### Laporan Retrieve All
GET http://localhost:3000/api/agenbni46/v1/getLaporanRetrieveAll?from=2022-10-01&to=2022-10-20

### Laporan Lpg Retrieve
GET http://localhost:3000/api/agenbni46/v1/getLaporanLpgRetrieve?from=2022-10-01&to=2022-10-20&start=0&length=20

### Fee Retrieve Al
GET http://localhost:3000/api/agenbni46/v1/getFeeRetrieveAll?start=0&length=20